# Generated by Django 4.0.3 on 2022-03-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zmembers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=35, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=35, verbose_name='Soyad')),
                ('phone', models.CharField(max_length=35, verbose_name='Telefon')),
                ('province', models.CharField(max_length=35, verbose_name='İl')),
                ('district', models.CharField(max_length=35, verbose_name='İlçe')),
                ('neighborhood', models.CharField(max_length=35, verbose_name='Mahalle')),
                ('address_description', models.TextField(max_length=255, verbose_name='Adres Tarifi')),
                ('address_title', models.TextField(max_length=50, verbose_name='Adres Başlığı')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
