# Generated by Django 4.0.3 on 2022-03-08 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zproduct', '0001_initial'),
        ('zmembers', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Mesaj İçeriği')),
                ('status', models.CharField(choices=[('New', 'Yeni'), ('Read', 'Okundu'), ('Close', 'Cevap Verildi')], default='New', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=45)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='zmembers.comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zproduct.product', verbose_name='Ürün Adı')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
    ]
