# Generated by Django 4.0.3 on 2022-03-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zmembers', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
