# Generated by Django 4.0.3 on 2022-03-08 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='slug',
        ),
    ]
