# Generated by Django 4.0.3 on 2022-03-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zpage', '0002_remove_aboutus_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='note',
            field=models.CharField(default='Not Alınmadı', max_length=70, verbose_name='Admin Notu'),
        ),
    ]
