# Generated by Django 4.0.3 on 2022-03-07 13:30

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Kategori Adı')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Taslak'), (1, 'Yayında'), (2, 'Sil')], verbose_name='Kategori Durumu')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=90, verbose_name='Marka')),
                ('title', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('barcode', models.CharField(max_length=20, unique=True, verbose_name='Barkod')),
                ('price', models.FloatField(verbose_name='Ürün Fiyatı')),
                ('discount_price', models.FloatField(blank=True, null=True, verbose_name='İndirimli Fiyatı')),
                ('stock', models.IntegerField(default=1)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ürün Detayları')),
                ('front_image', models.ImageField(default='product/default.png', help_text='372 x 431 Piksel Fotoğraf Olmalıdır.', upload_to='productfront/%Y/%m/%d/', verbose_name='Kapak Fotoğrafı')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zproduct.category')),
            ],
            options={
                'verbose_name_plural': 'Ürün İşlemleri',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zproduct.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=130, verbose_name='Fotoğraf Adı')),
                ('image', models.ImageField(default='product/default.png', help_text='1200x1200 piksel fotoğraf olmalıdır.', upload_to='product/%Y/%m/%d/')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zproduct.product')),
            ],
        ),
    ]
