# Generated by Django 4.0.3 on 2022-03-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zproduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.PositiveIntegerField(choices=[(0, 'Erkek'), (1, 'Kadın'), (2, 'Unisex'), (3, 'Çocuk')], default=0, verbose_name='Cinsiyet'),
        ),
    ]
